apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-cache
  name: redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
        - image: redis:7.4.0
          imagePullPolicy: Always
          name: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cache
  name: redis-cache
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-cache
  type: NodePort