apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: post-app
  name: post-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-app
  template:
    metadata:
      labels:
        app: post-app
    spec:
      containers:
        - image: mirasap/post-app:0.0.1
          imagePullPolicy: Always
          name: post-app
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: post-config
                  key: dbHost
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: post-config
                  key: dbName
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: password
            - name: JAVA_OPTS
              value: "-Xmx128m"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: post-config
                  key: redisHost
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: post-config
                  key: redisPort
---
apiVersion: v1
kind: Service
metadata:
  name: post-app
spec:
  selector:
    app: post-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort